osbuild-composer/src/blueprint-reference/blueprint-reference.md, osbuild-composer/src/developer-guide/developer-guide.md, osbuild-composer/src/developer-guide/osbuild-composer.md, osbuild-composer/src/developer-guide/osbuild.md, osbuild-composer/src/developer-guide/testing.md, osbuild-composer/src/user-guide/basic-concepts.md, osbuild-composer/src/user-guide/building-an-image-from-cli.md, osbuild-composer/src/user-guide/installation.md, osbuild-composer/src/user-guide/managing-repositories.md, osbuild-composer/src/user-guide/uploading-to-aws.md, osbuild-composer/src/user-guide/user-guide.md
This PR aims to provide a few suggestions on restructuring the `osbuild-composer` upstream documentation to make it modular.
Also, contains a few suggestions for markups and typos.
Many thanks!
=> Suggestions for the `osbuild-composer` upstream documentation

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/developer-guide/glossary.md
It is by far not exhaustive, but it could serve as a starting point.
=> Introduce glossary

cloud-dot-redhat/src/SUMMARY.md, cloud-dot-redhat/src/image-builder-in-stage-gui.md
This PR provides a suggestion to add a section on how to use the Image Builder in the stage environment, using the GUI. 
Many thanks!
=> Suggestions for the `cloud-dot-redhat` upstream documentation

cloud-dot-redhat/src/image-builder-in-stage.md
HI Martin, I am sending this PR with the following suggestions. 
There were typos on the following:
- deplyoment
- AWS
Suggestions to add the article to the following:
- in staging->in the staging
- Create new-> Create a new
Thank you!
=> Minor typo fixes suggestions

cloud-dot-redhat/src/prod/image-builder-api.md, cloud-dot-redhat/src/stage/image-builder-access.md
This PR suggests fixes on 2 typos founded across the documentation.
Many thanks!
=> WIP: Minor fix

osbuild-composer/src/developer-guide/glossary.md
Mention also the reasoning behind the concept of a compose.
=> glossary: Improve the description of "compose"

osbuild-composer/src/developer-guide/osbuild.md
This description strives to describe OSBuild in greater detail yet tries
not to contain anything that would quickly become outdated. It is also
not meant as an alternative for code comments, but rather complement
them for easier orientation in the codebase.
Explain also manifest v1 and v2 formats.
=> developer-guide: Extend osbuild description

osbuild-composer/src/user-guide/building-ostree-images.md
The quick brown fox jumps over the lazy anaconda.
=> user-guide: Fix typo

osbuild-composer/src/user-guide/managing-repositories.md
=> Improve the section about repository management

osbuild-composer/src/developer-guide/releasing.md
Also, update all the other sections where necessary to reflect the
current state of our release process/automation.
=> releasing: Make c9s a step-by-step instruction

osbuild-composer/src/developer-guide/releasing.md
Update the steps for CentOS Stream 9, taking the now productive centos-bot into account.
=> releasing: Update c9s description

osbuild-composer/src/developer-guide/releasing.md
Update some of the steps to add extra detail. Re-order the steps to add `centpkg build` step last.
=> releasing: update c9s steps

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/user-guide/uploading-to-azure.md
Because two clouds are better than one. 🤭
Signed-off-by: Major Hayden <major@redhat.com>
=> 📤 Add guide for Azure uploads

osbuild-composer/src/developer-guide/osbuild.md
Add a new section about osbuild stage testing during development
in the Developer Guide / OSBuild chapter. The section describes:
- how are stages unit-tested,
- how to verify modified filesystem tree after a stage run,
- special case when a new / modified stage requires a new python
dependency.
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> Add section about osbuild stage testing during development

osbuild-composer/src/user-guide/user-guide.md
Include a link to the internal guides for Red Hatters.
=> Add link to the internal guides

osbuild-composer/src/blueprint-reference/blueprint-reference.md
=> blueprint-reference: add `containers` section

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/user-guide/uploading-to-registry.md
=> Add guide how to upload container images

osbuild-composer/src/user-guide/container-auth.md
=> Small fixes to container credentials section

.github/workflows/build-guides.yml
Update workflow to upload build results and comment a download link.
=> include link to build artifact

osbuild-composer/src/user-guide/managing-repositories.md
Documentation for https://github.com/osbuild/osbuild-composer/pull/3230
=> Document new source check_repogpg flag and gpgkeys field.

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Explain how directory and file BP customizations can be used and what are the restrictions that apply when using it.
=> Blueprint: describe directory and file customizations

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Demonstrate various data formats for files customization
=> BP/files: link to TOML specification for string formatting

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/blueprint-reference/blueprint-reference.md
Some subheadings, clearer links. Started defining the attributes on the objects necessary. Put related content next to each other. Index per section.
=> clarify and reformat blueprint reference

osbuild-composer/src/blueprint-reference/blueprint-reference.md
This commit was missing from the last PR for a very weird reason.
=> Customization Rewrite (2)

src/image-builder-service/architecture.md
Add a status list of how open our service currently is.
=> service: Add open source service status

src/image-builder-service/architecture.md
Add hyperlinks where applicable. Also add the missing entry about "open roadmap".
=> service: Update open source status

src/SUMMARY.md, src/developer-guide/backporting.md
This page should make it easier to decide on when to backport fixes how.
=> developer-guide: Add page about backporting

src/SUMMARY.md, src/image-builder-on-premises/release-overview.md
This page will be auto-updated by guides-bot going forward.
=> on-premises: Add initial version of release overview

book.toml
The current navigation is becoming difficult to use/read as we have too many subpages.
=> navigation: Enable collapsing sections

README.md, src/SUMMARY.md, src/developer-guide/projects/osbuild-composer/localcloud.md
And cloudapi local cert setup.
=> Document local_save

src/image-builder-service/image-builder-koji.md
This is a follow-up for a change in osbuild-composer PR#3659.
[1] https://github.com/osbuild/osbuild-composer/pull/3659
=> Koji: add section describing metadata attached to builds

src/image-builder-on-premises/managing-repositories.md
=> on-prem/repos: list valid values for type field

src/developer-guide/general/workflow.md
I have tried to add some PR best practices that can be tested by CI and I have tried to make some of the paragraphs lists to improve readability.
=> workflow: Extend pr best practices

src/image-builder-on-premises/blueprint-reference.md
Add installation device support to the blueprint reference
=> on-prem: installation device blueprint reference

src/image-builder-on-premises/blueprint-reference.md
Use lines with fixed width for improved readability.
=> on-prem: fix line width to 80 chars
