cloud-dot-redhat/src/image-builder-in-stage.md
We should probably expose this in the API and just return the information,
but for now at least document it so people can easily find it.
=> image-builder-stage: clarify which region we default to

cloud-dot-redhat/src/image-builder-in-stage.md
The staging environment requires VPN access. Add a disclaimer to avoid confusing/disappointing people.
=> image-builder-stage: include disclaimier about VPN access

osbuild-composer/src/user-guide/managing-repositories.md
The previous version did not mention very important fact:
* there is no way to build other distributions
* the JSON file needs to have a well defined name
Fixes: #7
=> Clarify repository management

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/developer-guide/latest-rpm-builds.md
They are very useful, yet it can be difficult to find them and it is
pretty common to misinterpred HTTP 403 from AWS while clicking the link
in Jenkins output.
=> developer-guide: mention our upstream RPM repos

osbuild-composer/src/user-guide/edge-container+installer.md
I wrote the guide in a similar fashion to the OSTree image guide but in a separate document to present it as an alternative.
=> user-guide: new guide for edge-installer

osbuild-composer/src/developer-guide/osbuild.md
osbuild can run directly from a git checkout but it doesn't work with
selinux. Create a section that describes a workaround.
=> osbuild: new section about running osbuild from git checkout

osbuild-composer/src/user-guide/installation.md
Previous command was resulting in this error:
sudo systemctl enable --now cockpit
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
.wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
instance name specified.
=> Documentation: Fixes a type in the Web Ui section

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Adding a section to the `blueprint-reference` for filesystem support.
=> docs: add filesystem blueprint reference

osbuild-composer/src/developer-guide/releasing.md
This deprecates the RELEASING.md file in the osbuild-composer
repository.
Related PRs:
- https://github.com/osbuild/osbuild-composer/pull/1800
=> Add a release guide

osbuild-composer/src/blueprint-reference/blueprint-reference.md
The documentation seemed to imply that only RSA-public keys are supported, I tried to make it clearer.
=> Clarify blueprint reference re. SSH algorithms

osbuild-composer/src/developer-guide/releasing.md
These steps have been updated and moved to the internal guide, as they contain internal links.
=> Drop the (outdated) CS9 release guide

osbuild-composer/src/developer-guide/releasing.md
This update reflects the latest changes to our release actions (https://github.com/osbuild/release-action/tree/create-tag) and what is proposed here: https://github.com/osbuild/osbuild-composer/pull/2458
As a result of all these changes, we will have automated scheduled upstream releases with tags being pushed by a bot directly to the repository each Wednesday at 10UTC.
I would like us to keep the original section about creating a release tag because this workflow is still possible - and probably what we will use for components such as cockpit-composer.
=> releasing: Add a note about scheduled releases

osbuild-composer/src/user-guide/edge-container+installer.md
Fixes port in edge-container documentation to be `8080` instead of `8000`.
Actual:
```
$ composer-cli compose start-ostree --ref "rhel/edge/example" --url http://10.0.2.2:8000/repo/ empty edge-installer
```
Expected:
```
$ composer-cli compose start-ostree --ref "rhel/edge/example" --url http://10.0.2.2:8080/repo/ empty edge-installer
```
@achilleas-k can you take a quick look?
=> Fix edge-container port in example

osbuild-composer/src/developer-guide/workflow.md
Due to https://github.com/osbuild/osbuild-composer/pull/1933, the doc/news folder has been removed, so also remove the workflow documentation that requires to add news on that folder from the developer guide.
=> Remove deprecated 'Adding news' workflow on osbuild-composer

.github/workflows/build-guides.yml, osbuild-composer/book.toml
The mdbook definition needs to have the plantuml preprocessor enabled so the architectural diagram in
osbuild-composer/src/image-builder-service/architecture.md gets compiled and displayed correctly.
Therefore I touched the GitHub Action to install the necessary pre-requisites for compiling plantuml with mdbook.
I also modified the GitHub Action to run the build on every new pull request to verify everything builds correctly (similar to what we do with the internal guides), but skipping the publishing step.
=> Fix architecture diagram by adding plantuml

.github/workflows/build-guides.yml
Obviously the correct git syntax is refs/heads.
This fixes publishing on pushes to `main`
=> github-actions: Fix typo in conditional

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/blueprint-reference/blueprint-reference.md, osbuild-composer/src/user-guide/container-auth.md, osbuild-composer/src/user-guide/uploading-to-registry.md
Add a section how to configure container authorization and link from the blueprint guide as well as the container upload guide.
=> Add container credentials information

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/blueprint-reference/blueprint-reference.md, osbuild-composer/src/user-guide/oscap-remediation.md
Update the blueprint reference with info on how to specify OpenSCAP remediation customizations.
Document supported profiles for each distro.
Depends on: https://github.com/osbuild/osbuild-composer/pull/2695
=> Add OpenSCAP blueprint reference

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/developer-guide/osbuild-composer.md, osbuild-composer/src/image-builder-service/image-builder-composer.md, osbuild-composer/src/image-builder-service/image-builder-koji.md
- Add a section describing how Image Builder integrates with Koji.
- Move a note about Image Builder multitenancy from internal guide to the public one. This is relevant for the Koji integration, which is usually integrated as a separate tenant.
- Update the section describing local and remote APIs of `osbuild-composer`.
=> Document Koji integration + small fixes

osbuild-composer/src/blueprint-reference/blueprint-reference.md
The `/tmp` mountpoint was mistakenly left out
of the allowlist for previous distros.
=> Add /tmp to the list of supported mountpoints

osbuild-composer/src/blueprint-reference/blueprint-reference.md
=> blueprints: Fix typo in openscap example

osbuild-composer/src/image-builder-service/architecture.md
The frontend and backend were so far covered by a single box in the architecture diagram. If we want to link to repositories - and ideally, the version of the code running in operation - we need to be able to distinguish the two.
As a result, I've created an additional box for the frontend. I have also reworded the legend a bit to reflect this change.
=> Service: Include frontend in architecture diagram

osbuild-composer/src/image-builder-service/architecture.md, osbuild-composer/src/image-builder-service/architecture.svg
The architecture diagram now follows a similar style as we use in other places, e.g. koji-osbuild.
Furthermore, each component of our service now holds a direct link to the corresponding GitHub repository. For simplicity, I have linked the 'worker fleet' to the osbuild repository.
Also, the legend that was shown below the diagram explaining the authentication mechanisms between the pieces of the service has been omitted (see below).
Please note that the hyperlink rendering only works when including the svg file in markdown via {{#include }}. Furthermore, the svg's source cannot contain empty newlines or routines that might be interpreted as markdown. Otherwise it will fail to render correctly.
=> Service: Refresh architecture diagram w hyperlinks

.github/workflows/build-guides.yml, osbuild-composer/book.toml
As we don't have any uml diagrams in our docs anymore, we can remove the plantuml preprocessor from the GitHub Action. It was originally added in fcd8cffa07378ba911e4c2400237044415e86dde
=> github-action: Remove plantuml mdbook preprocessor

osbuild-composer/src/user-guide/managing-repositories.md
When I included a repo override, I had to restart the osbuild-composer service in order for `composer-cli sources info` to return the correct information.
This updates the guide to note this requirement and cleans up some of the Markdown syntax according to the Markdown linter in my IDE.
=> managing-repos: overrides require osbuild-composer restart

osbuild-composer/src/image-builder-service/architecture.svg
Update the SVG with the hashes of our service components currently running in production. This is necessary so we can update these hashes automatically going forward.
=> Service: Add hashes running in production

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Fix link to the detailed information page.
Unify RHEL versions spelling.
=> Fix OpenSCAP Support section

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/introduction.md
This content currently lives at https://osbuild.org/documentation, during the docs sprint we decided that that page will become a quick reference with links into the guides.
The content is now duplicated inside the guides instead.
=> introduction: duplicate documentation content

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Configuring a port range for the firewall customization is supported, but it was not clear how to do so.  This change provides an example.
=> blueprints: show port range example for firewalls

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/blueprint-reference/blueprint-reference.md, osbuild-composer/src/user-guide/repository-customizations.md
Add a brief explaination on the differences between payload repositories and custom repository configurations that get saved to the `/etc/yum.repos.d` directory of a built image.
Add the blueprint-reference for the blueprint repository customizations.
=> user-guide: explaination on custom repositories

osbuild-composer/src/blueprint-reference/blueprint-reference.md
It ends up that thanks to DNF we do support package name globbing, so document that they can use `*` and `?` in package names.
=> blueprint: Change the package name description

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Add info about the new ignition customization.
Please wait until osbuild/osbuild-composer#3161 gets merged to merge this (if approved oc).
=> blueprint-reference: add Ignition config section

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Add a note for the image types that don't support filesystem customizations.  This is a common point of confusion among users, especially for the Anaconda-based ISO image types.
Separate the image types where fs customizations don't make sense, to suggest that the others might get the support in the future.
=> blueprint: list image types that don't support filesystem customizations

osbuild-composer/src/blueprint-reference/blueprint-reference.md
Warn users that it is possible that customizations could be ignored silently, this is an often recurring problem in support channels and should be mentioned up front until we fix the root issue.
=> blueprints: customizations could be ignored

osbuild-composer/src/blueprint-reference/blueprint-reference.md
The Fedora `iot-raw-image` supports files and directories customization since PR #3303 [1]. Adjust the documentation accordingly.
[1] https://github.com/osbuild/osbuild-composer/pull/3303
=> Update files / dirs BP customizations WRT iot-raw-image.

osbuild-composer/src/image-builder-service/architecture.md
This is an initial stab at improving our architecture page. This page also serves as the landing page from the open source badge from our service, so we want to include a bit of `how to contribute` information there as well.
=> service: Add contribution section

osbuild-composer/src/image-builder-service/architecture.md
Add a sentence that echoes what users coming from our open source service badge (see screenshot below) read. In the future, the open source services logo will also go next to this sentence or in the section.
=> service: Add open source notice

osbuild-composer/src/SUMMARY.md, osbuild-composer/src/developer-guide/testing-strategy/rpmrepo.md, osbuild-composer/src/developer-guide/testing-strategy/testing-strategy.md
We want to retire the landing page on osbuild.org. In order to do that, we need to copy over any useful content that was on there.
This commit does that for RPMRepo.
=> developer-guide: import the RPMRepo documentation

.github/workflows/build-guides.yml
Adjust the relative path to account for the removal of the osbuild-composer folder.
=> gh action: Fix path

src/image-builder-service/architecture.md
While both of our Jira projects are public, we were missing links to them in our docs.
=> service: Add links to Jira

src/image-builder-service/architecture.md
Apart from adding a link to our open project roadmap, I also added brackets to make the links stand out a bit more visually.
=> service: Add roadmap link to OSS status

src/image-builder-on-premises/managing-repositories.md
If I'm reading the osbuild-composer's source code correctly, this parameter is currently totally unused, thus we can safely omit it from the documentation.
=> managing-repositories: remove system=false from sources

src/image-builder-on-premises/oscap-remediation.md
pre-defined -> predefined
Remedation -> Remediation
"the the" -> the
"The the" -> The
pacakge -> package
Please, let me know if I'm doing anything wrong.
Thank you!
=> oscap-remediation.md: Fix typos

src/blueprint-reference/blueprint-reference.html, src/user-guide/building-ostree-images.html, src/user-guide/managing-repositories.html, src/user-guide/uploading-to-cloud.html
These pages are referred to by the man pages of composer-cli, so we should redirect to their new location. This mechanism can also be used in the future to add redirects to other pages that have moved.
See also https://github.com/osbuild/weldr-client/pull/114
=> Add redirects for some pages

src/introduction.md
When user was navigating to developers guide using link on the main documentation page result was 404 error.
This PR fixes the link to point main index page of developer guide instead.
=> Fix: Update broken link

src/image-builder-on-premises/blueprint-reference.md
- update blueprint reference for OpenSCAP `datastream` customization option.
- add blueprint reference for OpenSCAP tailoring customizations
=> Autotailor guides

src/image-builder-service/image-builder-koji.md
Add a section how can one reproduce image builds locally, using the files and information attached to each Koji build.
=> Koji: add section about locally reproducing image builds

src/image-builder-on-premises/blueprint-reference.md
Update the blueprint reference to use the `minsize` keyword rather than the `size` keyword.
=> on-prem: filesystem minsize

src/image-builder-on-premises/blueprint-reference.md
Reflect the latest changes in the mountpoint policy in the documentation. In addition, simplify the sentence describing the support of filesystem customizations in RHEL versions.
The version of `osbuild/images` with the policy change landed in `osbuild-composer` and it will be included in the next v94 release.
=> BP reference: update section on filesystem customizations

src/image-builder-on-premises/blueprint-reference.md
Update the blueprint reference to document the
new system FIPS mode setup and update the examples
section with additional information.
Depends on https://github.com/osbuild/images/pull/253
Signed-off-by: Miguel Martín <mmartinv@redhat.com>
=> on-prem: fips mode blueprint reference

src/image-builder-on-premises/blueprint-reference.md
Extend the detailed description for all the customizations
present in the example blueprint.
Signed-off-by: Miguel Martín <mmartinv@redhat.com>
=> on-prem: extend example blueprint information

src/image-builder-on-premises/blueprint-reference.md
Adds the FDO section to on-prem, explains the different customization options.
=> blueprint: add FDO section
